# Generated by Django 4.0.3 on 2022-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('abbrev', models.CharField(blank=True, max_length=128, null=True)),
                ('institution', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('orcid', models.CharField(blank=True, max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'authors',
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorsReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('evaluator', 'Critical evaluator'), ('compiler', 'Compiler')], default='compiler', max_length=9)),
                ('order', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'authors/reports (join)',
                'db_table': 'authors_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier', models.CharField(blank=True, max_length=128, null=True)),
                ('purity', models.CharField(blank=True, max_length=128, null=True)),
                ('compnum', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'chemicals',
                'db_table': 'chemicals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=16)),
                ('significand', models.CharField(max_length=16)),
                ('exponent', models.IntegerField()),
                ('error', models.CharField(blank=True, max_length=16, null=True)),
                ('error_type', models.CharField(blank=True, max_length=8, null=True)),
                ('accuracy', models.PositiveIntegerField()),
                ('compnum', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'conditions',
                'db_table': 'conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('significand', models.TextField()),
                ('exponent', models.TextField()),
                ('error', models.TextField()),
                ('error_type', models.CharField(max_length=8)),
                ('accuracy', models.TextField()),
                ('component', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'data',
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datapoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('rownum', models.SmallIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'datapoints',
                'db_table': 'datapoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dataseries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=128)),
                ('seriesnum', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('independent set', 'Independent Data Series'), ('spectrum', 'Instrument Spectrum'), ('chromatogram', 'LC/GC/IC/SFC Chromatogram')], default='independent set', max_length=20)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'dataseries',
                'db_table': 'dataseries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('comments', models.CharField(blank=True, max_length=256, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'datasets',
                'db_table': 'datasets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identifiers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('inchi', 'InChI'), ('inchikey', 'InChIKey'), ('smiles', 'Canonical SMILES'), ('casrn', 'CASRN')], default='inchi', max_length=12)),
                ('value', models.CharField(max_length=1024)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'identifiers',
                'db_table': 'identifiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('abbrev', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('homepage', models.CharField(max_length=256)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'journals',
                'db_table': 'journals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quantities',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('symbol', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=512)),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'quantities',
                'db_table': 'quantities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('citation', models.CharField(blank=True, max_length=400, null=True)),
                ('publisher', models.CharField(blank=True, max_length=256, null=True)),
                ('abbrev', models.CharField(blank=True, max_length=128, null=True)),
                ('authors', models.CharField(blank=True, max_length=2048, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=6, null=True)),
                ('issue', models.CharField(blank=True, max_length=16, null=True)),
                ('startpage', models.CharField(blank=True, max_length=6, null=True)),
                ('endpage', models.CharField(blank=True, max_length=6, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('doi', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(choices=[('paper', 'Journal article'), ('book', 'Book'), ('dissertation', 'Dissertation'), ('thesis', 'Thesis'), ('report', 'Report'), ('communication', 'Communication'), ('chapter', 'Book Chapter'), ('patent', 'Patent')], default='paper', max_length=15)),
                ('comments', models.CharField(blank=True, max_length=512, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'references',
                'db_table': 'references',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferencesReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('original', 'Original Measurements Paper'), ('supplmental', 'Method Reference Paper')], default='original', max_length=12)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'refs/reports (join)',
                'db_table': 'references_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.CharField(max_length=8)),
                ('type', models.CharField(choices=[('evaluation', 'System evaluation'), ('compilation', 'Compilation')], default='compilation', max_length=11)),
                ('variables', models.CharField(blank=True, max_length=512, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('comments', models.CharField(max_length=1024)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'reports',
                'db_table': 'reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Substances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('casno', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('formula', models.CharField(blank=True, max_length=1024, null=True)),
                ('formula_html', models.CharField(blank=True, max_length=1024, null=True)),
                ('molweight', models.FloatField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'substances',
                'db_table': 'substances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubstancesSystems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compnum', models.CharField(choices=[('undefined', 'Change me!'), ('1', 'Component 1'), ('2', 'Component 2'), ('3', 'Component 3'), ('4', 'Component 4')], default='undefined', max_length=9)),
                ('role', models.CharField(choices=[('undefined', 'Change me!'), ('solute', 'Solute'), ('solvent', 'Solvent'), ('mutual', 'Mutual solubility')], default='undefined', max_length=9)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'subs/systems (join)',
                'db_table': 'substances_systems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('components', models.PositiveIntegerField(choices=[(2, 'Binary mixture'), (3, 'Ternary mixture'), (4, 'Quaternary mixture')], default=2)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'systems',
                'db_table': 'systems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('si', 'SI Base Unit'), ('siderived', 'SI Derived Unit'), ('siallowed', 'SI Allowed Unit'), ('cgs', 'Centimetre–gram–second Unit System'), ('imperial', 'Imperial Unit System')], default='si', max_length=9)),
                ('qudt', models.CharField(blank=True, max_length=32, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'units',
                'db_table': 'units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volumes',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('volume', models.CharField(blank=True, max_length=32, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('authors', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=128)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'volumes',
                'db_table': 'volumes',
                'managed': False,
            },
        ),
    ]
