# Generated by Django 5.0.3 on 2024-03-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='references',
            options={'managed': False, 'ordering': ['citation'], 'verbose_name_plural': 'references'},
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'managed': False, 'ordering': ['system__name'], 'verbose_name_plural': 'reports'},
        ),
        migrations.AlterModelOptions(
            name='systems',
            options={'managed': False, 'ordering': ['name'], 'verbose_name_plural': 'systems'},
        ),
    ]
