# Generated by Django 5.0.3 on 2024-04-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0002_alter_references_options_alter_reports_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(db_collation='utf8mb3_general_ci', max_length=16)),
                ('source', models.CharField(blank=True, choices=[('Calculated', 'Author calculation'), ('Compiler', 'Compiler calculation'), ('Evaluator', 'Evaluator calculation')], default='Compiler', max_length=10, null=True)),
                ('significand', models.CharField(db_collation='utf8mb3_general_ci', max_length=16)),
                ('exponent', models.IntegerField()),
                ('error', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=16, null=True)),
                ('error_type', models.CharField(blank=True, choices=[('absolute', 'Absolute'), ('relative', 'Relative'), ('SD', 'Std. Dev.'), ('%RSD', '% RSD'), ('CI', 'Conf. Interval')], db_collation='utf8mb3_general_ci', max_length=8, null=True)),
                ('accuracy', models.PositiveIntegerField(default=1)),
                ('compnum', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=128, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'suppdata',
                'db_table': 'suppdata',
                'managed': False,
            },
        ),
    ]
